import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Button, Container } from '@mui/material';
import { topButtonStyle } from '../styles/Pages';

const inter = Inter({ subsets: ['latin'] });

export default function Top() {
  return (
    <>
      <Head>
        <title>WAT Quizzer</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Container>
        <h1>WAT Quizzer</h1>
        <Button
          style={topButtonStyle}
          variant="contained"
          size="large"
          color="primary"
          href={'/quizzer' + process.env.NEXT_PUBLIC_URL_END}
        >
          Quizzer
        </Button>
        <Button
          style={topButtonStyle}
          variant="contained"
          size="large"
          color="secondary"
          href={'/englishBot' + process.env.NEXT_PUBLIC_URL_END}
        >
          English Quiz Bot
        </Button>
      </Container>
    </>
  );
}
