import Head from 'next/head';
import { Card, CardContent, CardHeader, Container } from '@mui/material';
import { useEffect, useState } from 'react';
import { Layout } from '@/components/templates/layout/Layout';
import { Title } from '@/components/ui-elements/title/Title';
import { getBook } from '@/common/response';
import { InputSayingState, PullDownOptionState } from '../../interfaces/state';
import { AddBookForm } from '@/components/ui-forms/settings/addBookForm/AddBookForm';
import { AddSayingForm } from '@/components/ui-forms/settings/addSayingForm/AddSayingForm';
import { SearchSayingSection } from '@/components/ui-forms/settings/searchSayingSection/SearchSayingSection';
import { EditSayingSection } from '@/components/ui-forms/settings/editSayingSection/EditSayingSection';
import { messageState } from '@/atoms/Message';
import { useRecoilState } from 'recoil';

type Props = {
  isMock?: boolean;
};

export default function Settings({ isMock }: Props) {
  const [booklistoption, setBooklistoption] = useState<PullDownOptionState[]>([]);
  const [bookName, setBookName] = useState<string>('');
  const [queryOfSaying, setQueryOfSaying] = useState<string>('');
  const [checkedIdList, setCheckedIdList] = useState<number[]>([] as number[]);
  const [inputSaying, setInputSaying] = useState<InputSayingState>({
    bookId: -1,
    saying: '',
    explanation: ''
  });
  const [message, setMessage] = useRecoilState(messageState);

  useEffect(() => {
    !isMock && getBook(setMessage, setBooklistoption);
  }, [isMock, setMessage]);

  const contents = () => {
    return (
      <>
        <Head>
          <title>設定</title>
          {/* <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" /> */}
        </Head>
        <Container>
          <Title label="WAT Quizzer - 設定"></Title>

          <Card
            variant="outlined"
            style={{
              margin: '10px 0'
            }}
          >
            <CardHeader title="格言設定" />
            <CardContent>
              <AddBookForm
                bookName={bookName}
                setBookName={setBookName}
                setMessageStater={setMessage}
                setBooklistoption={setBooklistoption}
              />
              <AddSayingForm
                inputSaying={inputSaying}
                booklistoption={booklistoption}
                setInputSaying={setInputSaying}
                setMessageStater={setMessage}
              />
              <SearchSayingSection
                queryOfSaying={queryOfSaying}
                setQueryOfSaying={setQueryOfSaying}
                setMessageStater={setMessage}
                setCheckedIdList={setCheckedIdList}
              />
              <EditSayingSection setMessageStater={setMessage} />
            </CardContent>
          </Card>
        </Container>
      </>
    );
  };

  return (
    <>
      <Layout mode="settings" contents={contents()} title={'設定'} />
    </>
  );
}
