CREATE DATABASE IF NOT EXISTS english_db;
USE english_db;

CREATE TABLE IF NOT EXISTS word
(
  id INT NOT NULL,
  name VARCHAR(256) NOT NULL,
  pronounce VARCHAR(256) NOT NULL,
  PRIMARY KEY(id)
) DEFAULT CHARACTER
  SET=utf8;
